version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: scg_test_proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: scg_test_server
    ports:
      - '3000:3000'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_DATABASE: sequelize
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: scg_test_mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scg_test
    ports:
      - '3306:3306'
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: scg_test_pma
    ports:
      - 8888:80
    links:
      - mysql
    environment:
      # PMA_PASSWORD: password
      # PMA_USER: root
      PMA_HOSTS: mysql
      PMA_PORTS: 3306
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
